sudo: required
addons:
  - chrome: stable

env:
  global:
    DISPLAY: ":99.0"

rvm:
  - 2.5.1
  - 2.4.4

before_install:
  - google-chrome-stable --version
  - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin/chromedriver
  - sudo sh -c 'curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent3.sh | sh'
  - nvm install 10
  # mini_portile2 requires bundler ~> 1.17
  - gem install bundler --version 1.17.3

install:
  - bin/setup
