sudo: required
addons:
  - chrome: stable

env:
  global:
    DISPLAY: ":99.0"

rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10

before_install:
  - google-chrome-stable --version
  - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin/chromedriver

install:
  - bundle -v
  - gem i bundler
  - sudo sh -c 'curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent3.sh | sh'
  - bin/setup
