rvm: 2.1.3

sudo: required

install:
  - wget http://packages.treasuredata.com.s3.amazonaws.com/2/ubuntu/precise/pool/contrib/t/td-agent/td-agent_2.2.0-0_amd64.deb
  - sudo dpkg -i td-agent_2.2.0-0_amd64.deb
  - bundle install --jobs=4 --retry=4
